url1=https://demoqa.com/
url2=https://www.naukri.com/
url3=https://www.facebook.com/
url4=https://demoqa.com/alerts
url5=https://www.javatpoint.com/
url6=https://demoqa.com/checkbox
url7=https://www.browserstack.com/
url8=https://demoqa.com/buttons
url9=http://demo.guru99.com/test/drag_drop.html
first=Selenium
last=Assignment
email=testing@gmail.com
password=secret78879